.Dd November 1, 2017
.Dt PASSGET
.Sh NAME
.Nm passget
.Nd get password
.Sh SYNOPSIS
.Nm
.Ar service
.Op username
.Sh DESCRIPTION
.Nm
reads password file from standard input and prints out a pass phrase to the standard output for an account matching a
.Ar service
pattern and optionally also matching an
.Ar username
pattern.
It prints only the first match if there is multiple matches, but it informs the user about this situation and exits with nonzero status.
.Pp
.Nm
prints the result only if the standard output is not a tty.
