.Dd April 23, 2017
.Dt PASSGET
.Sh NAME
.Nm passget
.Nd get password
.Sh SYNOPSIS
.Nm
.Ar pattern
.Sh DESCRIPTION
.Nm
reads password file from standard input and prints pass phrase to an account detected by
.Ar pattern
to standard output.
.Nm
prints the result only if the standard output is not tty.
